{% set name = "universal_pathlib" %}
{% set version = "v0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/Quansight/universal_pathlib/releases/download/{{ version }}/universal_pathlib-{{ version }}.tar.gz
  url: https://github.com/Quansight/universal_pathlib/archive/{{ version }}.tar.gz
  sha256: bd2ec9ef5f80f707bb06e8aa600d34559d184373d3e31e7848fa38d1426814cb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fsspec >=0.8.3
    

test:
  imports:
    - upath
    - upath.tests

about:
  home: https://github.com/Quansight/universal_pathlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pathlib api extended to use fsspec backends'
  dev_url: https://github.com/Quansight/universal_pathlib

extra:
  recipe-maintainers:
    - andrewfulton9
